server:
  port: 80
  servlet:
    encoding:
      charset: utf-8

spring:
  application:
    name: aVocado
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        open-in-view: false
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true

  ai:
    openai:
      api-key: YOUR_API_KEY # aVocado API 키 필요
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
