spring:
  application:
    name: aVocado
  ai:
    openai:
      api-key: YOUR_API_KEY #aVocado API 키 필요
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7

server:
  port: 80
