server:
  port: 80
  servlet:
    encoding:
      charset: utf-8

spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: cZVEosgybmtENqxFqach  # 여기에 실제 네이버 클라이언트 ID를 입력하세요.
            client-secret: bGiajnoVxp  # 여기에 실제 네이버 클라이언트 시크릿을 입력하세요.
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        open-in-view: false
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true

  ai:
    openai:
      api-key: YOUR_API_KEY  # 여기에 실제 OpenAI API 키를 입력하세요.
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
